[package]
name = "simon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
home = "0.5.4"
midir = "0.8.0"
midly = "0.5.2"
rand = "0.8"
